In [31]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/FabulousErin/Project_2/main/static/data/yield_data.csv')
df.head()

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,...,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BARLEY,"BARLEY - YIELD, MEASURED IN BU / ACRE",TOTAL,NOT SPECIFIED,77.5,NaN
1,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,BEANS,"BEANS, DRY EDIBLE, (EXCL CHICKPEAS) - YIELD, M...",TOTAL,NOT SPECIFIED,"1,966",NaN
2,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,CANOLA,"CANOLA - YIELD, MEASURED IN LB / ACRE",TOTAL,NOT SPECIFIED,"1,931",NaN
3,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,CHICKPEAS,"CHICKPEAS - YIELD, MEASURED IN LB / ACRE",TOTAL,NOT SPECIFIED,"1,625",NaN
4,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",TOTAL,NOT SPECIFIED,172,NaN

In [32]:
df = df.drop(["State ANSI", "Ag District", "Ag District Code", "County", "Zip Code", "Watershed", "CV (%)"], axis=1)

In [33]:
df.head()

,Program,Year,Period,Week Ending,Geo Level,State,County ANSI,Region,watershed_code,Commodity,Data Item,Domain,Domain Category,Value
0,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,0,BARLEY,"BARLEY - YIELD, MEASURED IN BU / ACRE",TOTAL,NOT SPECIFIED,77.5
1,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,0,BEANS,"BEANS, DRY EDIBLE, (EXCL CHICKPEAS) - YIELD, M...",TOTAL,NOT SPECIFIED,"1,966"
2,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,0,CANOLA,"CANOLA - YIELD, MEASURED IN LB / ACRE",TOTAL,NOT SPECIFIED,"1,931"
3,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,0,CHICKPEAS,"CHICKPEAS - YIELD, MEASURED IN LB / ACRE",TOTAL,NOT SPECIFIED,"1,625"
4,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,0,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",TOTAL,NOT SPECIFIED,172

In [40]:
df_Yield_Columndrops = df.drop(["Week Ending", "Program", "Period", "Geo Level", "County ANSI", "Region", "Domain", "Domain Category", "watershed_code"], axis=1)

In [41]:
df_Yield_Columndrops

,Year,State,Commodity,Data Item,Value
0,2020,US TOTAL,BARLEY,"BARLEY - YIELD, MEASURED IN BU / ACRE",77.5
1,2020,US TOTAL,BEANS,"BEANS, DRY EDIBLE, (EXCL CHICKPEAS) - YIELD, M...","1,966"
2,2020,US TOTAL,CANOLA,"CANOLA - YIELD, MEASURED IN LB / ACRE","1,931"
3,2020,US TOTAL,CHICKPEAS,"CHICKPEAS - YIELD, MEASURED IN LB / ACRE","1,625"
4,2020,US TOTAL,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",172
...,...,...,...,...,...
3911,2010,WYOMING,BARLEY,"BARLEY - YIELD, MEASURED IN BU / ACRE",98
3912,2010,WYOMING,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",123
3913,2010,WYOMING,OATS,"OATS - YIELD, MEASURED IN BU / ACRE",61
3914,2010,WYOMING,SUGARBEETS,"SUGARBEETS - YIELD, MEASURED IN TONS / ACRE",27
3915,2010,WYOMING,WHEAT,"WHEAT - YIELD, MEASURED IN BU / ACRE",32

In [43]:
yield_cleaned = df_Yield_Columndrops

In [44]:
yield_cleaned.head()

,Year,State,Commodity,Data Item,Value
0,2020,US TOTAL,BARLEY,"BARLEY - YIELD, MEASURED IN BU / ACRE",77.5
1,2020,US TOTAL,BEANS,"BEANS, DRY EDIBLE, (EXCL CHICKPEAS) - YIELD, M...","1,966"
2,2020,US TOTAL,CANOLA,"CANOLA - YIELD, MEASURED IN LB / ACRE","1,931"
3,2020,US TOTAL,CHICKPEAS,"CHICKPEAS - YIELD, MEASURED IN LB / ACRE","1,625"
4,2020,US TOTAL,CORN,"CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",172