In [28]:
import pandas as pd

In [29]:
csv_path='production_data.csv'

In [34]:
production_df = pd.read_csv(csv_path)

production_df

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,...,Zip Code,Region,watershed_code,Watershed,Commodity,Data Item,Domain,Domain Category,Value,CV (%)
0,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN DISTILLERS OIL (CDO) ...",TYPE OF OPERATION,TYPE OF OPERATION: (DRY MILL PLANT),"1,708,687",NaN
1,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GERM MEAL - PRODUCTIO...",TYPE OF OPERATION,TYPE OF OPERATION: (WET MILL PLANT),"697,251",NaN
2,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GLUTEN FEED, MEDIUM P...",TYPE OF OPERATION,TYPE OF OPERATION: (WET MILL PLANT),"3,445,892",NaN
3,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GLUTEN FEED, WET, 40 ...",TYPE OF OPERATION,TYPE OF OPERATION: (WET MILL PLANT),"2,601,936",NaN
4,SURVEY,2020,YEAR,NaN,NATIONAL,US TOTAL,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GLUTEN MEAL, HIGH PRO...",TYPE OF OPERATION,TYPE OF OPERATION: (WET MILL PLANT),"1,128,108",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1969,SURVEY,2020,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,WHEAT,"WHEAT - PRODUCTION, MEASURED IN BU",TOTAL,NOT SPECIFIED,"2,340,000",NaN
1970,SURVEY,2020,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,WHEAT,"WHEAT, WINTER - PRODUCTION, MEASURED IN $",TOTAL,NOT SPECIFIED,"10,647,000",NaN
1971,SURVEY,2020,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,WHEAT,"WHEAT, WINTER - PRODUCTION, MEASURED IN BU",TOTAL,NOT SPECIFIED,"2,340,000",NaN
1972,SURVEY,2020,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,WHEAT,"WHEAT, WINTER, RED, HARD - PRODUCTION, MEASURE...",TOTAL,NOT SPECIFIED,97,NaN
1973,SURVEY,2020,YEAR,NaN,STATE,WYOMING,56.0,NaN,NaN,NaN,...,NaN,NaN,0,NaN,WHEAT,"WHEAT, WINTER, WHITE, HARD - PRODUCTION, MEASU...",TOTAL,NOT SPECIFIED,3,NaN

In [64]:
col_df= production_df.drop(columns=['Week Ending','State ANSI','Ag District','Ag District Code','County','County ANSI','Zip Code','Region','Domain Category','watershed_code','Watershed', 'CV (%)'])
col_df

,Program,Year,Period,Geo Level,State,Commodity,Data Item,Domain,Value
0,SURVEY,2020,YEAR,NATIONAL,US TOTAL,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN DISTILLERS OIL (CDO) ...",TYPE OF OPERATION,"1,708,687"
1,SURVEY,2020,YEAR,NATIONAL,US TOTAL,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GERM MEAL - PRODUCTIO...",TYPE OF OPERATION,"697,251"
2,SURVEY,2020,YEAR,NATIONAL,US TOTAL,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GLUTEN FEED, MEDIUM P...",TYPE OF OPERATION,"3,445,892"
3,SURVEY,2020,YEAR,NATIONAL,US TOTAL,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GLUTEN FEED, WET, 40 ...",TYPE OF OPERATION,"2,601,936"
4,SURVEY,2020,YEAR,NATIONAL,US TOTAL,ALCOHOL COPRODUCTS,"ALCOHOL COPRODUCTS, CORN GLUTEN MEAL, HIGH PRO...",TYPE OF OPERATION,"1,128,108"
...,...,...,...,...,...,...,...,...,...
1969,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT - PRODUCTION, MEASURED IN BU",TOTAL,"2,340,000"
1970,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT, WINTER - PRODUCTION, MEASURED IN $",TOTAL,"10,647,000"
1971,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT, WINTER - PRODUCTION, MEASURED IN BU",TOTAL,"2,340,000"
1972,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT, WINTER, RED, HARD - PRODUCTION, MEASURE...",TOTAL,97
1973,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT, WINTER, WHITE, HARD - PRODUCTION, MEASU...",TOTAL,3

In [65]:
clean_df=col_df[col_df['Data Item'].str.contains('MEASURED IN \$')]
clean_df

,Program,Year,Period,Geo Level,State,Commodity,Data Item,Domain,Value
10,SURVEY,2020,YEAR,NATIONAL,US TOTAL,BARLEY,"BARLEY - PRODUCTION, MEASURED IN $",TOTAL,"753,314,000"
12,SURVEY,2020,YEAR,NATIONAL,US TOTAL,BEANS,"BEANS, DRY EDIBLE, (EXCL CHICKPEAS) - PRODUCTI...",TOTAL,"1,005,619,000"
33,SURVEY,2020,YEAR,NATIONAL,US TOTAL,CANOLA,"CANOLA - PRODUCTION, MEASURED IN $",TOTAL,"602,504,000"
35,SURVEY,2020,YEAR,NATIONAL,US TOTAL,CHICKPEAS,"CHICKPEAS - PRODUCTION, MEASURED IN $",TOTAL,"83,210,000"
37,SURVEY,2020,YEAR,NATIONAL,US TOTAL,CHICKPEAS,"CHICKPEAS, LARGE - PRODUCTION, MEASURED IN $",TOTAL,"68,565,000"
...,...,...,...,...,...,...,...,...,...
1964,SURVEY,2020,YEAR,STATE,WYOMING,HAY & HAYLAGE,"HAY & HAYLAGE - PRODUCTION, MEASURED IN $",TOTAL,"449,816,000"
1965,SURVEY,2020,YEAR,STATE,WYOMING,HAY & HAYLAGE,"HAY & HAYLAGE, (EXCL ALFALFA) - PRODUCTION, ME...",TOTAL,"130,237,000"
1966,SURVEY,2020,YEAR,STATE,WYOMING,HAY & HAYLAGE,"HAY & HAYLAGE, ALFALFA - PRODUCTION, MEASURED ...",TOTAL,"319,579,000"
1968,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT - PRODUCTION, MEASURED IN $",TOTAL,"10,647,000"
1970,SURVEY,2020,YEAR,STATE,WYOMING,WHEAT,"WHEAT, WINTER - PRODUCTION, MEASURED IN $",TOTAL,"10,647,000"